#!/usr/bin/env node
/**
 * Ghost Engine - Proof Loop Engine
 * Every close -> case study -> content -> ads -> more closes
 * Run: node proof-loop.js trigger <name> <details...>
 */

const fs = require("fs");
const path = require("path");

const BASE = "/home/workspace/Ghost-Monitization-Engine";
const PROOF_DIR = BASE + "/proof";
const CLOSE_LOG = BASE + "/scripts/close-log.jsonl";
const LESSONS = BASE + "/lessons-learned.md";
const MEMORY = BASE + "/MEMORY.md";

if (!fs.existsSync(PROOF_DIR)) fs.mkdirSync(PROOF_DIR, { recursive: true });

function triggerProofLoop(clientData) {
  const id = Date.now();
  const { name, platform, followers, tier, investment, timeline, result, quote } = clientData;

  console.log("\n[PROOF LOOP] Triggered for: " + (name || "Client"));
  console.log("  Tier: " + tier + " | Investment: " + investment);
  console.log("  Result: " + result);

  // 1. Generate case study
  const caseStudy = generateCaseStudy(clientData, id);
  writeFile(PROOF_DIR + "/" + id + "-case-study.md", caseStudy);
  console.log("  [OK] Case study created");

  // 2. Generate 3 authority posts
  const posts = generateAuthorityPosts(clientData, id);
  writeFile(PROOF_DIR + "/" + id + "-authority-post-1.md", posts[0]);
  writeFile(PROOF_DIR + "/" + id + "-authority-post-2.md", posts[1]);
  writeFile(PROOF_DIR + "/" + id + "-authority-post-3.md", posts[2]);
  console.log("  [OK] 3 authority posts created");

  // 3. Generate breakdown
  const breakdown = generateBreakdown(clientData, id);
  writeFile(PROOF_DIR + "/" + id + "-breakdown.md", breakdown);
  console.log("  [OK] Breakdown created");

  // 4. Log to close log
  const logEntry = JSON.stringify({
    ts: new Date().toISOString(),
    type: "proof_loop_triggered",
    client: name,
    platform,
    followers,
    tier,
    investment,
    result,
    quote,
    files: [
      id + "-case-study.md",
      id + "-authority-post-1.md",
      id + "-authority-post-2.md",
      id + "-authority-post-3.md",
      id + "-breakdown.md"
    ]
  });
  fs.appendFileSync(CLOSE_LOG, logEntry + "\n", "utf8");
  console.log("  [OK] Close log updated");

  // 5. Update MEMORY.md
  updateMemory(clientData);
  console.log("  [OK] MEMORY.md updated");

  // 6. Update lessons-learned.md
  updateLessons(clientData);
  console.log("  [OK] lessons-learned.md updated");

  console.log("\n[PROOF LOOP] All files in: " + PROOF_DIR);
  console.log("\nNEXT: Post authority-post-1 TODAY. Use breakdown as carousel this week.");
}

function generateCaseStudy(d, id) {
  return `# CASE STUDY: How ` + (d.name || "This Creator") + ` Made ` + (d.result || "$X" ) + ` in ` + (d.timeline || "X days") + `

## The Client
- **Name:** ` + (d.name || "Creator") + `
- **Platform:** ` + (d.platform || "TikTok") + `
- **Followers:** ` + (d.followers || "X") + `
- **Problem:** Monetization gap

## The Offer
- **Tier:** ` + (d.tier || "Quick Flip") + `
- **Investment:** ` + (d.investment || "$X") + `
- **Timeline:** ` + (d.timeline || "X days") + `

## The Result
**` + (d.result || "Revenue increased significantly") + `**

## What We Built
` + (d.details || "Monetization system installed. Revenue engine running.") + `

## Testimonial
> "` + (d.quote || "This changed everything.") + `"
` + (d.name ? "- " + d.name : "") + `

## The Gap (Before vs After)
| | Before | After |
|---|---|---|
| Monthly Revenue | $0 | ` + (d.result || "$X") + ` |
| Monetization | None | Full engine |
| Content | Posting | Converting |

---
*Generated by Ghost Engine on ` + new Date().toISOString().split("T")[0] + `*
`;
}

function generateAuthorityPosts(d, id) {
  const name = d.name || "a creator";
  const tier = d.tier || "Quick Flip";
  const result = d.result || "significant revenue";
  const timeline = d.timeline || "a short time";

  return [
    `# POST 1 - Result Hook\nJust turned ` + (d.followers || "X") + ` followers into ` + result + ` in ` + timeline + `.\n\n` + name + ` had the attention. Didnt have the system.\n\n48 hours later? Money machine installed.\n\nThe gap is never the content. Its the monetization layer.\n\n(If you have an audience and no revenue system -- lets talk.)`,

    `# POST 2 - Pattern Interrupt\n"Views dont pay your bills"\n\nI keep saying this. ` + name + ` finally heard it.\n\n` + (d.followers || "X") + ` followers. Zero monthly revenue.\n\nNow? ` + result + ` in ` + timeline + `.\n\nThe problem was never the content. It was never the followers.\n\nIt was the missing money system.\n\n(If this sounds familiar -- I probably already know your numbers. DM me.)`,

    `# POST 3 - Education + CTA\nHow to know if you need a monetization engine:\n\n1. You have an audience (any platform)\n2. You have engagement (people actually show up)\n3. You have ZERO consistent monthly revenue\n\nIf all 3 are true -- you dont have a content problem.\n\nYou have a backend problem.\n\nI fix the backend.\n\n(DM me "engine" if you want to see how it works.)`
  ];
}

function generateBreakdown(d, id) {
  return `# THE BREAKDOWN: ` + (d.name || "This Creator") + `

**Platform:** ` + (d.platform || "TikTok") + `
**Followers:** ` + (d.followers || "X") + `
**Tier:** ` + (d.tier || "Quick Flip") + `
**Investment:** ` + (d.investment || "$X") + `
**Result:** ` + (d.result || "$X") + ` in ` + (d.timeline || "X days") + `

---

## BEFORE
- Audience: Yes
- Revenue: $0/mo
- Monetization: None
- Offers: None

## AFTER
- Audience: Still growing
- Revenue: ` + (d.result || "$X/mo") + `
- Monetization: Full engine
- Offers: ` + (d.tier || "Installed") + `

## WHAT WE BUILT
` + (d.details || "Monetization system, offer stack, backend automation." || "Full revenue engine installed.") + `

## WHAT THIS PROVES
You dont need more followers. You need a system.

---

*Ghost Engine -- We build the money machine.*`;
}

function updateMemory(d) {
  const entry = `
## Win: ` + (d.name || "Client") + `
- **Date:** ` + new Date().toISOString().split("T")[0] + `
- **Platform:** ` + (d.platform || "Unknown") + `
- **Tier:** ` + (d.tier || "Quick Flip") + `
- **Result:** ` + (d.result || "Win logged") + `
- **Key insight:** ` + (d.insight || "See lessons-learned.md") + ``;

  if (fs.existsSync(MEMORY)) {
    fs.appendFileSync(MEMORY, entry, "utf8");
  }
}

function updateLessons(d) {
  const entry = `
## Close: ` + (d.name || "Client") + `
- **Date:** ` + new Date().toISOString().split("T")[0] + `
- **Tier:** ` + (d.tier || "Quick Flip") + `
- **What worked:** ` + (d.what_worked || "See case study") + `
- **What to remember:** ` + (d.lesson || "Log this win.") + ``;

  if (fs.existsSync(LESSONS)) {
    fs.appendFileSync(LESSONS, entry, "utf8");
  }
}

function writeFile(path, content) {
  fs.writeFileSync(path, content, "utf8");
}

function showProofs() {
  if (!fs.existsSync(PROOF_DIR)) { console.log("No proofs yet."); return; }
  const files = fs.readdirSync(PROOF_DIR).filter(f => f.endsWith(".md")).sort().reverse();
  console.log("\n===== PROOF FILES =====");
  files.forEach(f => {
    const stats = fs.statSync(PROOF_DIR + "/" + f);
    console.log("  " + f + " (" + Math.round(stats.size / 1024) + "KB)");
  });
}

const cmd = process.argv[2];
if (cmd === "trigger") {
  const args = process.argv.slice(3);
  triggerProofLoop({
    name: args[0] || "Client",
    platform: args[1] || "TikTok",
    followers: args[2] || "10K",
    tier: args[3] || "Quick Flip",
    investment: args[4] || "$990",
    timeline: args[5] || "48 hours",
    result: args[6] || "Revenue installed",
    quote: args[7] || "This was exactly what I needed."
  });
} else if (cmd === "list") {
  showProofs();
} else {
  console.log("Usage:");
  console.log("  node proof-loop.js trigger <name> <platform> <followers> <tier> <investment> <timeline> <result> [quote]");
  console.log("  node proof-loop.js list");
  console.log("\nExample:");
  console.log("  node proof-loop.js trigger \"Alex\" \"TikTok\" \"45K\" \"Full Engine\" \"$4970\" \"2 weeks\" \"First $10K month\" \"I finally have a system.\"");
}
